# Generated by Django 4.0.3 on 2022-04-07 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningSession',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.post')),
                ('started_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('canceled', models.BooleanField(default=False)),
            ],
            bases=('post.post',),
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('PRS', 'PRESENDENT'), ('VPR', 'VICE_PRESEDENT'), ('SEC', 'SECRETARY'), ('TRS', 'TREASURY'), ('CLM', 'CELL_MANAGER'), ('MBR', 'MEMBER')], default='MBR', max_length=3)),
                ('date_of_join', models.DateTimeField(auto_now=True)),
                ('state', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Pending'), (-1, 'Disabled')], default=0)),
                ('presentation', models.TextField(blank=True, max_length=1000)),
                ('notif_setting', models.CharField(choices=[('NONE', 'no notifications'), ('INAP', 'in-app only'), ('MAIL', 'email only'), ('BOTH', 'in-app and email')], default='BOTH', max_length=4)),
                ('permission', models.SmallIntegerField(choices=[(1, 'all the permissions'), (2, 'manage training session'), (3, 'manage projects'), (4, 'mamange joining sessions'), (5, 'verify a training registration')], null=True)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.cell')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
