# Generated by Django 4.0.3 on 2022-03-15 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id_cell', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id_club', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='images/club_logos')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('main_pic', models.ImageField(blank=True, upload_to='images/post_pics/')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('INF', 'INFORMATIVE'), ('TRN', 'TRAINING_SESSION'), ('JNS', 'JOINING_SESSION'), ('FRM', 'FORM')], default='INF', max_length=3)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.club')),
            ],
        ),
        migrations.CreateModel(
            name='JoiningSession',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mainApp.post')),
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('canceled', models.BooleanField(default=False)),
            ],
            bases=('mainApp.post',),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CP1', 'Cp1'), ('CP2', 'Cp2'), ('SEECS1', 'Seecs1'), ('SEECS2', 'Seecs2'), ('SEECS3', 'Seecs3'), ('G11', 'G11'), ('G12', 'G12'), ('G13', 'G13'), ('GIL1', 'Gil1'), ('GIL2', 'Gil2'), ('GIL3', 'Gil3'), ('GCDSTE1', 'Gcdste1'), ('GCDSTE2', 'Gcdste2'), ('GCDSTE3', 'Gcdste3'), ('RSSP1', 'Rssp1'), ('RSSP2', 'Rssp2'), ('RSSP3', 'Rssp3')], default='CP1', max_length=7)),
                ('phone_number', models.CharField(max_length=13)),
                ('avatar', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('PRS', 'PRESENDENT'), ('VPR', 'VICE_PRESEDENT'), ('SEC', 'SECRETARY'), ('TRS', 'TREASURY'), ('CLM', 'CELL_MANAGER'), ('MBR', 'MEMBER')], default='MBR', max_length=3)),
                ('date_of_join', models.DateTimeField(auto_now=True)),
                ('state', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Pending'), (-1, 'Disabled')], default=0)),
                ('presentation', models.TextField(blank=True, max_length=1000)),
                ('notif_setting', models.CharField(choices=[('NONE', 'no notifications'), ('INAP', 'in-app only'), ('MAIL', 'email only'), ('BOTH', 'in-app and email')], default='BOTH', max_length=4)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.cell')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.club'),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.post')),
                ('limited_places', models.SmallIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('cencelled', models.BooleanField(default=False)),
                ('presented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('mainApp.post',),
        ),
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.trainingsession')),
            ],
        ),
    ]
