# Generated by Django 4.0 on 2021-12-31 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id_cell', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id_club', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pic_url', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('INF', 'INFORMATIVE'), ('TRN', 'TRAINING_SESSION'), ('STF', 'STUFFING_SESSION')], default='INF', max_length=3)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('limited_places', models.SmallIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('cencelled', models.BooleanField(default=False)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.post')),
                ('presented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.trainingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='StuffingSession',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('canceled', models.BooleanField(default=False)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.post')),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_join', models.DateTimeField(auto_created=True)),
                ('grade', models.CharField(choices=[('PRS', 'PRESENDENT'), ('VPR', 'VICE_PRESEDENT'), ('SEC', 'SECRETARY'), ('TRS', 'TREASURY'), ('CLM', 'CELL_MANAGER'), ('MBR', 'MEMBER')], default='MBR', max_length=3)),
                ('state', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Pending'), (-1, 'Disabled')], default=0)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.cell')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.club')),
                ('stuffing_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.stuffingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.club'),
        ),
    ]
