# Generated by Django 4.0.3 on 2022-03-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joiningsession',
            name='id_session',
        ),
        migrations.AlterField(
            model_name='joiningsession',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.post'),
        ),
    ]
