# Generated by Django 4.0 on 2022-02-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='nom',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cell',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='notif_setting',
            field=models.CharField(choices=[('NONE', 'no notifications'), ('INAP', 'in-app only'), ('MAIL', 'email only'), ('BOTH', 'in-app and email')], default='BOTH', max_length=4),
        ),
        migrations.AddField(
            model_name='membership',
            name='presentation',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.cell'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('INF', 'INFORMATIVE'), ('TRN', 'TRAINING_SESSION'), ('STF', 'STUFFING_SESSION'), ('FRM', 'FORM')], default='INF', max_length=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.URLField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.post')),
            ],
        ),
    ]
