# Generated by Django 4.0.3 on 2022-03-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_joiningsession_id_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingregistration',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
