# Generated by Django 4.0 on 2022-02-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_nom_club_name_cell_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pic_url',
        ),
    ]
