# Generated by Django 4.0.3 on 2022-04-01 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0001_initial'),
        ('mainApp', '0003_trainingregistration_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joiningsession',
            name='post_ptr',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='club',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingregistration',
            name='session',
        ),
        migrations.RemoveField(
            model_name='trainingregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='post_ptr',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='presented_by',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club'),
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='JoiningSession',
        ),
        migrations.DeleteModel(
            name='MemberShip',
        ),
        migrations.DeleteModel(
            name='TrainingRegistration',
        ),
        migrations.DeleteModel(
            name='TrainingSession',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
