# Generated by Django 4.0 on 2022-02-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_post_pic_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StuffingSession',
            new_name='JoiningSession',
        ),
    ]
