# Generated by Django 4.0 on 2022-02-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_membership_stuffing_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_of_join',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
