# Generated by Django 4.0 on 2022-02-26 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_membership_date_of_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.cell'),
        ),
    ]
