# Generated by Django 4.0 on 2022-02-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_membership_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='cencelled',
        ),
    ]
