# Generated by Django 4.0 on 2022-03-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainApp', '0015_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CP1', 'Cp1'), ('CP2', 'Cp2'), ('GE1', 'Ge1'), ('GE2', 'Ge2'), ('GE3', 'Ge3'), ('G11', 'G11'), ('G12', 'G12'), ('G13', 'G13'), ('GIL1', 'Gil1'), ('GIL2', 'Gil2'), ('GIL3', 'Gil3'), ('GS1', 'Gs1'), ('GS2', 'Gs2'), ('GS3', 'Gs3'), ('RSSP1', 'Rssp1'), ('RSSP2', 'Rssp2'), ('RSSP3', 'Rssp3')], default='CP1', max_length=5)),
                ('phone_number', models.CharField(max_length=13)),
                ('avatar', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
