# Generated by Django 4.0 on 2022-03-07 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainApp', '0016_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('INF', 'INFORMATIVE'), ('TRN', 'TRAINING_SESSION'), ('JNS', 'JOINING_SESSION'), ('FRM', 'FORM')], default='INF', max_length=3),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='level',
            field=models.CharField(choices=[('CP1', 'Cp1'), ('CP2', 'Cp2'), ('SEECS1', 'Seecs1'), ('SEECS2', 'Seecs2'), ('SEECS3', 'Seecs3'), ('G11', 'G11'), ('G12', 'G12'), ('G13', 'G13'), ('GIL1', 'Gil1'), ('GIL2', 'Gil2'), ('GIL3', 'Gil3'), ('GCDSTE1', 'Gcdste1'), ('GCDSTE2', 'Gcdste2'), ('GCDSTE3', 'Gcdste3'), ('RSSP1', 'Rssp1'), ('RSSP2', 'Rssp2'), ('RSSP3', 'Rssp3')], default='CP1', max_length=7),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', to_field='username'),
        ),
    ]
