# Generated by Django 4.0 on 2022-03-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
