# Generated by Django 4.0 on 2022-03-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_alter_club_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic_url',
            field=models.ImageField(blank=True, upload_to='static/images/post_pics'),
        ),
    ]
