# Generated by Django 4.0 on 2022-03-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_post_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
