# Generated by Django 4.0 on 2022-03-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_alter_club_logo_alter_post_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(upload_to='static/images/club_logos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic_url',
            field=models.ImageField(blank=True, upload_to='static/images/post_pics'),
        ),
    ]
