# Generated by Django 4.0 on 2022-03-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_alter_club_logo_alter_post_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pic_url',
        ),
    ]
