# Generated by Django 4.0 on 2022-03-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_remove_post_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_pic',
            field=models.ImageField(blank=True, upload_to='static/images/post_pics/'),
        ),
    ]
